#! /bin/bash
#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin (info provided by Anton Lokhmotov)
#
if [ "$CK_GPU_FREQ_GOVERNOR" != "" ]; then
  governor=$CK_GPU_FREQ_GOVERNOR
fi

echo "    Setting min/max frequency according to GOVERNOR POLICY=$governor ..."
echo $governor | sudo tee /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/governor
